

spring:
  datasource:
    url: jdbc:${SQL_NAME:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:test}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}